---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.hello-world: glob:master-*
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: mareimorsy/hello-world:1.3
        ports:
        - containerPort: 8080
